### ISSUE TITLE
Linux Adjustments needed

### ISSUE THREAD

**Issue by psycho-driver** [dannygaray60/funemustation#3]
Hi!  Out of the box the latest release doesn't work quite right in linux.  There's a couple of spots in the code where '\\' is hardcoded as a file delimiter.  I was having problems both with /path/to\rom not launching as well as /path/to/rom\media (a new file) vs. /path/to/rom/media being created.  I also added in some QoL improvements for people who already have a bunch of metadata scraped from Skyscraper for Pegasus.
[fes-linux-qol.patch.txt](https://github.com/dannygaray60/funemustation/files/5946078/fes-linux-qol.patch.txt)

**Comment by TheJackiMonster** [comment]
I think your patch using a variable path separator is more Windows specific than Godot recommends. ^^'

> For the sake of supporting as many platforms as possible, Godot only accepts UNIX-style path separators (/). These work on all platforms, including Windows.

Reference from [Godot documentation](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html)

**Comment by psycho-driver** [comment]
Hi Tobias,
If you look at the places being patched in the code they're using a hard-coded windows delimeter '\\' which was keeping it from working right in linux.  I assumed changing it to '/' would work for windows too but I don't have any way of testing it, thus the check.
Thanks,

    On Thursday, February 11, 2021, 4:24:31 PM CST, Tobias Frisch <notifications@github.com> wrote:  
 
 


I think your patch using a variable path separator is more Windows specific than Godot recommends. ^^'


For the sake of supporting as many platforms as possible, Godot only accepts UNIX-style path separators (/). These work on all platforms, including Windows.


Reference from Godot documentation
